baseURL = "https://hugosite.crownlabs.polito.it/"
languageCode = "en-us"
title = "Project Work"
theme = "hugo-learn"

[params]
  themeVariant = "green"
  disableLandingPageButton = true

[outputs]
 home = [ "HTML", "RSS", "JSON"]
