# Workflow with checkout and docker-build-push
# using official Docker action for build/push steps
on:
  push:
    branches: [ main ]

jobs:

  build-publish:

    runs-on: ubuntu-latest

    steps:
    
    # Use action to checkout repo
    # Hugo themes are git submodules: "submodules: true" needed
    - name: Check out code
      uses: actions/checkout@v2
      with:
        submodules: true
          
    # Use official action to setup Docker Buildx (needed for following steps)
    # Docker Buildx is needed for docker/build-push-action
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    
    # Use official action to login to Docker Hub
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_PSW }}
        
    # Use official action to build and push Docker image
    - name: Build and push Docker image
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: paolabelmonte/hugo-site:v0
    
    # Show Docker image digest using output of previous actions
    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
    
