# Test workflow Paola
name: Docker build and publish

on:
  push:
    branches: [ main ]
  #pull_request:
    #branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2
      with:
        submodules: true
        
    - name: Get current time
      uses: 1466587594/get-current-time@v2
      id: time
      with:
        format: YYYYMMDD-HHMM
 
    - name: Output current time
      run: echo "Current time" ${{ steps.time.outputs.formattedTime }}  
 
    - name: Output Run ID
      run: echo "github.run_id" ${{ github.run_id }}
    - name: Output Run Number
      run: echo "github.run_number" ${{ github.run_number }}
 
