#Test env GIT variabes an date/time action
name: Docker build and publish

on:
  push:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2
      with:
        submodules: true
        
    - name: Output Run ID
      run: echo "GITHUB_RUN_ID" ${{ github.run_id }}
    - name: Output Run Number
      run: echo "GITHUB_RUN_NUMBER" ${{ github.run_number }}
    - name: Output SHA Commit
      run: echo "GITHUB_SHA" ${{ github_sha }} 
      
    - name: Get current time
      uses: 1466587594/get-current-time@v2
      id: time
      with:
        format: YYYYMMDD-HHMM
 
    - name: Output current time
      run: echo "Current time" ${{ steps.time.outputs.formattedTime }}  
 
    - name: Use current time        
      env:
         TIME: "${{ steps.time.outputs.time }}"
         R_TIME: "${{ steps.time.outputs.readableTime }}"
         F_TIME: "${{ steps.time.outputs.formattedTime }}"
         YEAR: "${{ steps.time.outputs.year }}"
         DAY: "${{ steps.time.outputs.day }}"
      run: echo $TIME $R_TIME $F_TIME $YEAR $DAY
 
