# Workflow using github.sha as tag for Docker image
name: Docker build and publish

on:
  push:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    
    # Use action to checkout repo
    # Hugo themes are git submodules: "submodules: true" needed
    - name: Check out code
      uses: actions/checkout@v2
      with:
        submodules: true
          
    # Use github.sha as tag for Docker image
    - name: Build and push Docker image
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: paolabelmonte/hugo-site
        tags: ${{ github.sha }}
        registry: docker.io
        dockerfile: Dockerfile
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_PSW }}

    # Use action to perform replamcement of IMG_TAG in template-deploy.yaml
    # after replacement save the file as my-deploy.yaml
    - name: Generate deploy yaml
      uses: danielr1996/envsubst-action@1.0.0
      with:
        input: template-deploy.yaml
        output: my-deploy.yaml
      env:
        IMG_TAG: ${{ github.sha }}
    
    # Use action to apply my-deploy.yaml to a K8s cluster
    # secrets.KUBECONFIG stores kubeconfig file with all cluster information
    - name: Deploy website
      uses: giorio94/kubectl-oidc-action@1.1.0
      with:
        kubeconfig: ${{ secrets.KUBECONFIG }}
        args: apply -f my-deploy.yaml
